db_name = "astrodb-template"  # Will be used to name db file
data_path = "data/" # relative path to JSON files
felis_path = "schema.yaml" # relative path to felis schema YAML file
lookup_tables = [
    "Publications",
    "Telescopes",
    "Instruments",
    "PhotometryFilters",
    "Versions",
    "RegimeList",
    "AssociationList",
    "SourceTypeList",
    "ParameterList",
    "CompanionList"
    ]
    