[database settings]
lookup_tables = [
    "Publications",
    "Telescopes",
    "Instruments",
    "PhotometryFilters",
    "Versions",
    "RegimeList",
    "AssociationList",
    "SourceTypeList",
    "ParameterList",
    "CompanionList"]
db_data_path = "data/"
felis_path = "schema/schema.yaml"
db_name = "astrodb-template.sqlite"