# This workflow will install Python dependencies,
# run the python script to generate the database,
# and push it back to the repo.

name: Generate Database SQLite file

on:
  workflow_dispatch:  # manual execution
  release:
    types: [published]
  push:  # remove this once we finish testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install astrodb_utils

    - name: Generate sqlite (file) database
      run: |
        # Generate database
        python -c "from astrodb_utils.loaders import build_db_from_json; build_db_from_json(settings_file='database.toml')"
        # TODO: Update with actual command to generate the database
      working-directory: .

    - name: Create release copy
      run: |
        # Get release tag
        release_tag=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')
        echo "Release tag: $release_tag"

        # Check if workflow is running on a release
        if [[ ${{ github.event_name }} == "release" ]]; then
          # Copy database file with release tag
          cp astrodb-template.sqlite astrodb-template-${release_tag}.sqlite
        fi

    - name: Commit database file
      run: |
        if [[ `git status --porcelain` ]]; then            
          git config user.name "${{ secrets.USER_LOGIN }}"
          git config user.email "${{ secrets.USER_ID }}+${{ secrets.USER_LOGIN }}@users.noreply.github.com"
          git add *.sqlite
          git commit -m "Updating database"
          git push    
        else
          echo "No changes were detected. git commit push action skipped."
        fi
      shell: bash
# The user email is {user.id}+{user.login}@users.noreply.github.com. See users API: https://api.github.com/users/github-actions%5Bbot%5D
