# This workflow will install Python dependencies,
# run the python script to generate the database,
# and push it back to the repo.

name: Generate Database SQLite file

on:
  workflow_dispatch:  # manual execution
  release:
    types: [published]
  push: # for temporary testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install astrodb_utils

    - name: Generate sqlite (file) database
      run: |
        # Generate database
        build_db_from_json database.toml
      working-directory: .
      shell: bash

    - name: Create release copy
      run: |
        # Get release tag
        release_tag=${{ github.event.release.tag_name }}

        echo "Event name: ${{ github.event_name }}"
        echo "Release tag: $release_tag"

        # Check if workflow is running on a release
        if [[ ${{ github.event_name }} == "release" ]]; then
          # Copy database file with release tag
          cp astrodb-template.sqlite astrodb-template-${release_tag}.sqlite

        else
          echo "Not running as a release: No release copy created."
        fi

    - name: Commit database file
      run: |
        if [[ `git status --porcelain` ]]; then            
          git config user.name "${{ secrets.USER_LOGIN }}"
          git config user.email "${{ secrets.USER_ID }}+${{ secrets.USER_LOGIN }}@users.noreply.github.com"

          # Adding database file
          git add *.sqlite
          git commit -m "Updating database"
          git push

          # Tag handling (move the tag to this commit if it is a release)
          if [[ ${{ github.event_name }} == "release" ]]; then
            # Get release tag
            release_tag=${{ github.event.release.tag_name }}
            echo "Release tag: $release_tag"

            # Remove existing tag in local and remove
            git tag -d $release_tag
            git push origin :refs/tags/$release_tag

            # Replace the tag
            git tag -fa $release_tag

            # Push the tag
            git push origin $release_tag

          fi
        else
          echo "No changes were detected. git commit push action skipped."
        fi
      shell: bash
