# This workflow will install Python dependencies,
# run the python script to generate the database,
# and push it back to the repo.

name: Generate Database

on:
  workflow_dispatch:  # manual execution
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install astrodb_utils

    - name: Generate sqlite (file) database
      run: |
        # TODO: Update with actual command to generate the database
        echo "Generating database..."
      working-directory: .

    - name: Commit database file
      run: |
        if [[ `git status --porcelain` ]]; then            
          git config user.name "${{ secrets.USER_LOGIN }}"
          git config user.email "${{ secrets.USER_ID }}+${{ secrets.USER_LOGIN }}@users.noreply.github.com"
          git add astrodb-template.sqlite
          git commit -m "Updating database"
          git push    
        else
          echo "No changes were detected. git commit push action skipped."
        fi
      shell: bash
# The user email is {user.id}+{user.login}@users.noreply.github.com. See users API: https://api.github.com/users/github-actions%5Bbot%5D
