# Run astrodb-utils using this branch of the template

name: Test astrodb-utils with this template

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      scripts_branch:
        description: 'Branch of astrodb_utils to use'
        type: string
        default: "main"
        required: true

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout utils repo
      uses: actions/checkout@v5
      with:
        repository: astrodbtoolkit/astrodb_utils
        ref: ${{ inputs.scripts_branch }}

    - name: Checkout template database repo to subdirectory
      uses: actions/checkout@v5
      with:
        path: tests/astrodb-template-db

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install astrodb_utils and dependencies needed for running tests
      run: |
        python -m pip install --upgrade pip
        pip install .[test]

    - name: Confirm branches
      run: |
        # Settings for the main directory
        git config --get remote.origin.url
        git branch --show-current

        # Settings for the astrodb-template-db directory (no branch name if HEAD)
        cd tests/astrodb-template-db/
        git config --get remote.origin.url
        git branch --show-current
        cd ../..

    - name: Test astrodb_utils with current branch of template
      run: |
        pytest
